### PR TITLE
Event based dispatcher

### PR DESCRIPTION
**Pull request by dehort**
The idea here is to try to make the websocket logic just deal with websockets.  The websocket layer will deal with the "queuing" layer on top of it by passing protocol.Message objects back and forth.

This PR modifies the ResponseDispatcher (renamed to ResponseReactor) so that it runs as a separate go routine for each websocket connection (each receptor websocket connection will have its own ResponseReactor instance) and dispatches the protocol.Message objects to the appropriate handler.

This PR introduces handlers for the handshake, payload and routing table messages.  These handlers get registered with the ResponseDispatcher.

The websocket reader go routine will read a chunk of data, marshal the data into a protocol.Message and send that over a channel to the ResponseReactor.  The ResponseReactor will read the protocol.Message from the channel, lookup the handler for the message type and give the message to the handler instance for processing.

TODO:
- [x] create a layer on top of the handlers to accumulate the data (capabilities, routing table data, etc).
- [x] create a top layer Receptor facade object that allows the web api layer (job receiver, connection status handler, etc) to invoke operations synchronously while hiding the lower level complexity
- [x] finish implementing the handlers
- [ ] handle write timeouts that can happen in the handshake_handler code (add a select to the write channel handling code in the handshake_handler)
- [ ] figure out a better way to pass the kafka writer into the payload handler _or_ decompose the payload handler into different objects (this will likely be required in order to dispatch to kafka and dispatch synchronously)
- [x] verify that the handlers are only taking what is required (don't pass unused variables)
- [x] fix the disconnect handler
- [x] pass the context from the websocket up to the ReceptorService so that any go routines spawned by the ReceptorService, Dispatcher, etc can be shutdown
- [x] fix the ConnectionManager so that it deals with the Receptor object instead of a Connection object
- [x] add ping to the openapi doc
- [x] add ping to the README
- [ ] add a configurable time out for the synchronous ping operation
- [x] rename Connection object to Transport
- [ ] make the async-to-sync timeout configurable
- [ ] split up the ReceptorService god object
- [ ] diagram the interactions
- [ ] add a bunch of tests (we should be able to unit test the individual handlers, build some automated integration tests to make sure the over all application works, etc)

### CODE REVIEW

**Comment by Jason-RH** [comment]
@dehort Are we closing this PR in favor of https://github.com/RedHatInsights/platform-receptor-controller/pull/56?

**Comment by dehort** [comment]
@Jason-RH nah, I was planning on merging #56 into the event_based_dispatcher branch where we can continue working on it.

**Comment by Jason-RH** [comment]
:+1:

**Comment by dehort** [comment]
@Jason-RH This PR is somewhat incomplete and way too big.  Is there anything you want to change before this gets merged into master?

**Comment by Jason-RH** [comment]
I'd like to use the new ResponseReactor to wire up kafka messaging properly, but I was planning on waiting till this got merged to master. I'm fine with merging and just fixing anything that comes up.

**Pull request merged**
